package flickr.gui.inputforms

import java.awt.{Dimension, GridLayout}
import javax.swing.{JComboBox, JLabel, JPanel}

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

class ComboInput() extends JPanel {
  /*
  |rome   |176810403|487258|
  |roma   |164069421|389562|
  |italy  |144645932|395968|
  |italia |82824661 |161284|
  |lazio  |32189896 |81257 |
  |nikon  |22812475 |28362 |
  |vatican|21402398 |63334 |
  |rom    |20666826 |46239 |
  |street |20373598 |14316 |
  |europe
   */


  var jLabel1: JLabel = null
  var jComboBox1: JComboBox[String] = null

  initComponents()

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings(Array("unchecked")) private // <editor-fold defaultstate="collapsed" desc="Generated Code">
  def initComponents(): Unit = {
    jLabel1 = new JLabel
    jComboBox1 = new JComboBox[String]

    setPreferredSize(new Dimension(760, 80))
    setLayout(new GridLayout(2, 2, 20, 0))
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER)

    add(jLabel1)
    add(new JLabel())
    add(jComboBox1)
    add(new JLabel())


    // </editor-fold>                        }
    // Variables declaration - do not modify

    // End of variables declaration
  }

}