package flickr.gui.inputforms

import java.awt.{Dimension, GridLayout}
import javax.swing.{JLabel, JPanel, JSpinner, SpinnerNumberModel}

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

class IntInput(min: Int, max: Int, value: Int, step: Int) extends JPanel {

  val model =
    new SpinnerNumberModel(value, min, max, step);
  var jLabel1: JLabel = null
  var jSpinner1: JSpinner = null

  initComponents()

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings(Array("unchecked")) private // <editor-fold defaultstate="collapsed" desc="Generated Code">
  def initComponents(): Unit = {
    jLabel1 = new JLabel

    jSpinner1 = new JSpinner(model)

    setPreferredSize(new Dimension(760, 80))
    setLayout(new GridLayout(2, 2, 20, 0))
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER)

    add(jLabel1)
    add(new JLabel())
    add(jSpinner1)
    add(new JLabel())


    // </editor-fold>                        }
    // Variables declaration - do not modify

    // End of variables declaration
  }

}